import bg1 from "./imgs/bg1.png"
import image1 from "./imgs/image1.jpg"
import image2 from "./imgs/image2.jpg"
import image3 from "./imgs/image3.jpg"



const Data = [
    {
        navbar:{
            logo:"Clark",
            li1:"Home",
            li2:"About",
            li3:"Resume",
            li4:"Services",
            li5:"Skills",
            li6:"Projects",
            li7:"My Blog",
            li8:"Contact",
        },
        section1:{
            s1t1:"HELLO !",
            s1t2:"I'm ",
            s1t3:"Clark",
            s1t4:"Thompson",
            s1t5:"A Freelance  Web Designer",
            s1btn1:"HIRE ME",
            s1btn2:"MY WORKS",
            s1img1:bg1,
        },
        section2:{
            s2img1:'',
            s2t1:"About Me",
            s2t2:"A small river named Duden flows by their place and supplies it with the necessary regelialia.",
            s2t3:"Name :",
            s2t4:"Clark Thompson",
            s2t5:"Date of birth :",
            s2t6:"January 01, 1987",
            s2t7:"Address :",
            s2t8:"San Francisco CA 97987 USA",
            s2t9:"Zip code :",
            s2t10:"1000",
            s2t11:"Email :",
            s2t12:"clarkthomp@gmail.com",
            s2t13:"Phone :",
            s2t14:"+1-2234-5678-9-0",
            s2t15:"120" ,
            s2t16:"Project complete",
            s2t17:"DOWNLOAD CV",
        },
        section3:{
            s3t1:"Resume",
            s3t2:"A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.",
            s3t3:"2014-2015",
            s3t4:"Master Degree of Design",
            s3t5:"CAMBRIDGE UNIVERSITY",
            s3t6:"A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.",
            s3t7:"2014-2015",
            s3t8:"Art & Creative Director",
            s3t9:"CAMBRIDGE UNIVERSITY",
            s3t10:"A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.",
            s3t11:"2014-2015",
            s3t12:"Wordpress Developer",
            s3t13:"CAMBRIDGE UNIVERSITY",
            s3t14:"A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.",
            s2t15:"DOWNLOAD CV",
        },
        section4:{
            s4t1:"Services",
            s4t2:"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia",
            s4ic1:"",
            s4t3:"WEB DESIGN",
            s4ic2:"",
            s4t4:"PHOTOGRAPHY",
            s4ic3:"",
            s4t5:"WEB DEVELOPER",
            s4ic4:"",
            s4t6:"APP DEVELOPING",
            s4ic5:"",
            s4t7:"BRANDING",
            s4ic6:"",
            s4t8:"PRODUCT STRATEGY",
        },
        section5:{
            s5t1:"My Skills",
            s5t2:"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia",
            s5t3:"Photoshop",
            s5t4:"90%",
            s5t5:"HTML5",
            s5t6:"95%",
            s5t7:"WordPress",
            s5t8:"jQuery",
            s5t9:"85%",
            s5t10:"CSS3",
            s5t11:"90%",
            s5t12:"SEO",
            s5t13:"80%",
        },
        section7:{
            s7t1:"Our Blog",
            s7t2:"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia",
            s7img1:image1,
            s7t3:"JUNE 21, 2019 ADMIN  3",
            s7t4:"Why Lead Generation is Key for Business Growth",
            s7t5:"A small river named Duden flows by their place and supplies it with the necessary regelialia.",
            s7img2:image2,
            s7t3:"JUNE 21, 2019 ADMIN  3",
            s7t4:"Why Lead Generation is Key for Business Growth",
            s7t5:"A small river named Duden flows by their place and supplies it with the necessary regelialia.",
            s7img3:image3,
        },
            Footer:{
            ftrt1:"About",
            ftrt2:"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
            ftrli1:"Links",
            ftrli2:"Home",
            ftrli3:"About",
            ftrli4:"Services",
            ftrli5:"Projects",
            ftrli6:"Contact",
            ftrli7:"Services",
            ftrli8:"Web Design",
            ftrli9:"Web Development",
            ftrli10:"Business Strategy",
            ftrli11:"Data Analysis",
            ftrli12:"Graphic Design",
            ftrli13:"Have a Questions?",
            ftrli14:"203 Fake St. Mountain View, San Francisco, California, USA",
            ftrli15:"+2 392 3929 210",
            ftrli16:"info@yourdomain.com",
            ftrli17:"Copyright ©2023 All rights reserved | This template is made with  by Colorlib",
        }
    }
]

export default Data